server:
  port: 8000
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/humandb
    driver-class-name: org.mariadb.jdbc.Driver
    username: human
    password: human1234
  
  output:
    ansi:
      enabled: always

logging:
  level:
    '[site.metacoding.humancloud]': DEBUG
